### ISSUE TITLE
files.PutFileReturnsDifferentVersion test has buggy version check

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/wopi-validator-core#74]
I think commit 18d3894 was incomplete. Changes are needed to save state properly from Unlock requests (I think).

**Comment by tylerbutler** [comment]
Looks like it's actually caused by JSON.NET deserializing strings as Dates automatically.

**Comment by tylerbutler** [comment]
Reactivating since the fix wasn't complete.

**Comment by Cobster** [comment]
Just noticed this test is failing for me.  I was having trouble figuring out why the validation service was expecting the Version to be an empty string on the second CheckFileInfo request.  As it seems to be doing the correct thing as defined by the spec.  Then I stumbled across this issue.  

Going to refrain from modifying my system until this issue is closed and I can retest.
