### ISSUE TITLE
UserPrincipalName is reported as an unknown property

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/wopi-validator-core#83]
The [docs](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/CheckFileInfo.html) mention `UserPrincipalName` in the properties of the `CheckFileInfo` response, but the validator rejects it as an unknown property:

>   Fail: FullCheckFileInfoSchema
>     CheckFileInfo, response code: 200 OK
>       Unknown Properties: UserPrincipalName
>     Re-run command: .\wopivalidator.exe -n FullCheckFileInfoSchema -w http://localhost:13958/api/tenant/foobar/wopi/files/d3301821-fddc-4751-b49f-5396cd6c6d6e -t eyJhbGciOiJSUzI1NiIsImtpZCI6IjA1NTU0MDM1QTk2MjA4NjMzMjczNEEyM0VDNTUzQzExRjFENDlGRTMiLCJ4NXQiOiJCVlZBTmFsaUNHTXljMG9qN0ZVOEVmSFVuLU0iLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiI3OGIzMjc2ZS1iNWZlLTQzMjctYTE2Ni0wYjViNjUxNjU0ZTQiLCJmaWxlSWQiOiJkMzMwMTgyMS1mZGRjLTQ3NTEtYjQ5Zi01Mzk2Y2Q2YzZkNmUiLCJwZXJtaXNzaW9uIjoiUmVhZCIsIm5iZiI6MTU3MjQ1MzU3MywiZXhwIjoxNTcyNDU3MTczLCJpYXQiOjE1NzI0NTM1NzN9.B_8njZ8s9e3H_UYfJTmK97HSU_JiyUB0A3R-4QAxhjqhMy-r10LtoFE8Ao3LB3KnqXW8x0StAzIX_PEHFmcEMaxKMYVf9t_32F1Ho4gdz_AMfSB65DxxHiOGKWz-WCR1g3cyqiIc88aln9bgFTIsB5mW9suB9W-aTaiEuSAl6TeyBmkZ5dysVrFIvSblHYa-iZ8bUN7HRTnBS3-ky0FdtuZA4sCxbWNrO_K10kc6aSQU9ROL7MQlfLMpJMkBgJ7yqrBv3DcxzlMqRN--DAPNbRybVpBZfkI5-zdAgeT4mHAlsNRlZ_0HMiXC-vThPFMM-qwS9BUIX30WWVW1azdncw -l 1572457173870

Which is correct, the docs or the validator?

**Comment by tylerbutler** [comment]
Think of WOPI like HTTP. There are lots of optional HTTP headers, but in some scenarios these "optional" headers are required. The HTTP RFC defines the semantic meaning of some headers but ultimately whether they are required or not depends on the scenario. For example, the Authorization header is optional - but not if you're sending requests to a site that requires auth.

WOPI is the same. Just because something is optional in the protocol doesn't mean it's *always* optional. The validator tests we have today are specifically for the Cloud Storage Partner Program.

So to answer your question, both the docs and the validator are correct.

**Comment by thomaslevesque** [comment]
> So to answer your question, both the docs and the validator are correct.

Well, given that we need to pass the tests to be able to publish a WOPI host implementation, I'd say that property is actually mandatory... I treat it as such, anyway.

**Comment by v-stefansi** [comment]
We are in the process of closing WOPI Validator GitHub.  If you still need help with this issue, please reach out to the CSPP partner Yammer channel or contact csppteam@microsoft.com.
